### ISSUE TITLE
Improve logging in Broker

### ISSUE THREAD

**Issue by jarovo** [SatelliteQE/broker#125]
When debug logging option is selected, the broker doesn't output much more of information then when the info level is selected. It should output more lines about what it does like:
```
[I 210803 15:23:32 commands:230] Pulling local inventory
[I 210803 15:23:33 commands:231] Making GET request [XXX] on [awx...redhat.com] ...
[I 210803 15:23:35 commands:231] Response for request [XXX]:
some content
of what it got
from the Tower
server
````

**Comment by ogajduse** [comment]
I could not agree more with the suggestion! broker logging is definitely missing information about the request that broker makes to AnsibleTower provider as well as the response to that request.

I consider the debug level as something that should be used only for debugging purposes, but how can you debug broker if it does not provide you much of the information.

I myself as a broker user would welcome a PR for this functionality.

**Comment by JacobCallahan** [comment]
Broker itself isn't making the requests directly to tower, it is the awxkit library. I also don't want to enable full debug logging for awxkit as that is way too verbose.
So we need to find a healthy medium. Every call doesn't need to be logged, but more can be. Can you elaborate on when you needed more information than what current debug logging doesn't provide?

**Comment by ogajduse** [comment]
I would suggest implementing @jaryn's work for a `--debug-level trace`.

I remember the case when the user passed invalid args to the `checkout` and the broker error message was just KeyError or some other standard Python exception. I do not exactly remember what the arguments were. Any debug log that would tell me any details about the HTTP request that awxkit creates would help me in the investigation.
