### ISSUE TITLE
`new_expire_time` value is interpreted as integer

### ISSUE THREAD

**Issue by peterdragun** [SatelliteQE/broker#132]
If I use default value for `new_expire_time` which is "+172800" this is interpreted as number 172800. Problem is that Tower expects either time to be added or timestamp in the future or exact time.
Reproducer:
using latest version of broker with not `new_expire_time` variable set in config or in config with +.
`broker extend --all`

**Comment by ogajduse** [comment]
If the `new_expire_time` is passed as a command-line argument, broker interprets it as string, which is correct.

**Comment by ogajduse** [comment]
This is a Dynaconf bug, but I would like to keep this one open until the Dynaconf issue is resolved.
https://github.com/rochacbruno/dynaconf/issues/585

**Comment by JacobCallahan** [comment]
the dynaconf issue has been resolved in the latest release

**Comment by ogajduse** [comment]
FYI, I just found out that the latest Dynaconf 3.1.7 does not include the fix yet.
