### ISSUE TITLE
Ansible Automation Platform API path changes

### ISSUE THREAD

**Issue by bherrin3** [SatelliteQE/broker#147]
## Problem 

With the addition of Ansible Automation Platform, the URL for API changes for `workflows` and `job-templates`

Other changes are more than likely part of the update, but these are the most relevant to primary functionality.

## Proposed Solution

Add a new provider, `AnsibleController`.

This will allow for distinct changes with Ansible Automation Platform while still retaining support for legacy Ansible Tower

This will also allow seamless changes from one provider to another with simple changes to the `broker_settings.yml` (or at the same time) without requiring a hard switchover. 

Examples and new APIs can be provided.

**Comment by rdrazny** [comment]
To be more precise - the API path for submitting jobs to Controller (AAP 2+ name for Ansible Tower) remains same. What have changed is the UI URL format. Currently, broker prints out an URL in the following form:
```
https://tower.example.com/#/workflows/XXX
```
where XXX is the ID of a job in Tower.

AAP 2+ uses following link to UI:
```
Workflows
https://tower.example.com/#/jobs/workflow/XXX
```
The job ID is identical, but the format is different. There can be `/output` (visualizations for workflows , or Ansible output for  job templates) or `/details` (job metadata) appended to the URL, but these are not mandatory. Controller redirects to `/output` by default.
