### ISSUE TITLE
Return of AnsibleTower workflows and job-templates should include inventory and description

### ISSUE THREAD

**Issue by bherrin3** [SatelliteQE/broker#191]
##  Problem

* There are now MANY inventories that exist for users to deploy and the default inventory may not be the correct location to deploy (they may want to override run-time)
* By default, the description of the workflow / job-template (which is in the API) is not passed back to the user when requesting information about a workflow /  job-template

## Solution

* Add both of these as a return to the following
```
(broker) ➜  broker git:(master) ✗ broker providers AnsibleTower --workflow deploy-base-rhel
[INFO 230217 10:48:36] Querying provider AnsibleTower
[INFO 230217 10:48:36] Using token authentication
[INFO 230217 10:48:40] Accepted additional nick fields:
    deploy_scenario: baserhel
    deploy_rhel_version: ''
    host_type: host 
```

```
(broker) ➜  broker git:(master) ✗ broker providers AnsibleTower --job-template satlab-tower-set-swap
[INFO 230217 10:49:57] Querying provider AnsibleTower
[INFO 230217 10:49:57] Using token authentication
[INFO 230217 10:49:58] Accepted additional nick fields:
    set_swap_default: 4096
    target_host: ''
```

**Comment by ogajduse** [comment]
Just FTR, broker is still not able to choose the instance of AnsibleTower to get the WF/JT details from. See #127
