### ISSUE TITLE
from_inventory ContentHostError when hostnames are missing in inventory file

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/broker#195]
Currently, there is an issue of hostnames not being returned when syncing an inventory file from AT. With such inventory file the from_inventory function fails with:

`*** robottelo.hosts.ContentHostError: A valid hostname must be provided`

which causes stops local execution of robottelo tests regardless of server.hostnames being present:
https://github.com/SatelliteQE/robottelo/blob/135820d863ea5455584f283d5142ffe099564996/pytest_fixtures/core/xdist.py#L28

Arguably the exception could be treated in robottelo's align_to_satellite function. 
Workaround: empty the INVENTORY_FILTER setting in robottelo, this way it takes the server.hostnames as expected

**Comment by ogajduse** [comment]
I would suggest modifying the broker ina way that would be satisfied with `ip` if `hostname` is null/not defined.
