### ISSUE TITLE
Test suite needs to be updated to look for broker_settings.yaml in ~/.broker

### ISSUE THREAD

**Issue by Griffin-Sullivan** [SatelliteQE/broker#212]
Currently, the tests are hard coded to search for `broker_settings.yaml` in the root directory of broker. After https://github.com/SatelliteQE/broker/pull/206, we now need to look for the file in `~/.broker/`. See https://github.com/SatelliteQE/broker/pull/211 for an example.

**Comment by Gauravtalreja1** [comment]
@tpapaioa @JacobCallahan Can this issue be closed as completed?

**Comment by JacobCallahan** [comment]
@Gauravtalreja1 on second look, yes. There is a larger issue around config files used in testing that will be resolved later.

**Comment by ogajduse** [comment]
@JacobCallahan Can you please link the PR that resolved it for better traceability?
