### ISSUE TITLE
[RFE] Implement `broker --version` 

### ISSUE THREAD

**Issue by kedark3** [SatelliteQE/broker#22]
# Issue 

When using broker, sometimes it can be hard to figure out what `settings.yaml` file it is using. It is similar to `ansible` where `ansible.cfg` file can be specified using an EnvVar, or can be located in `pwd` or user's home dir or under `/etc/ansible`. Since there are multiple ways to specify the file they make it obvious with `ansible --version` or by specifying the file location information on stdout during every playbook execution(if ran with `-v` for verbose). It also helps user know which python executable Ansible will be using as there could be multiple python versions installed in various locations on a given system.

# Requested solution

Please implement a way for broker to provide `broker -v/--version` to help users know what `settings.yaml`, python executable and potentially what inventory file is being used by the broker. As well as `broker` executable path itself. 

This information can be useful in debugging issues when users may run into problems with broker failing to read correct settings or not finding inventory file etc. 

# Example of `ansible --version`

```
 ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kkulkarni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
```

# Alternative solution

Currently readme does not specify the broker needs to execute from the same directory where the settings/inventory files are. We should update readme to reflect that OR allow user to explicitly set the path for these manually, explicitly so that user could invoke broker from any location on his system as long as it is configured to look at correct settings file. Sort of like `git config --global` where we can set global config for git to use no matter where we are calling it from.

**Comment by tstrych** [comment]
I will just add :) 
currently you can list all packages via via `pip list`
And you can run specifically  `pip show broker` to get:
```
Name: broker
Version: 0.0.11
Summary: The infrastructure middleman.
Home-page: https://github.com/SatelliteQE/broker
Author: Jacob J Callahan
Author-email: jacob.callahan05@@gmail.com
License: GNU General Public License v3
Location: location_path
Requires: awxkit, click, dynaconf, logzero, pyyaml, ssh2-python
Required-by:
```

**Comment by kedark3** [comment]
Well it is true in case of Ansible as well but still they have `ansible --version` with some different info than what Pip would provide. That's what I was going for.
