### ISSUE TITLE
Feature request: Support authentication via ssh-agent

### ISSUE THREAD

**Issue by dosas** [SatelliteQE/broker#246]
[ssh2-python](https://ssh2-python.readthedocs.io/en/latest/session.html#ssh2.session.Session.agent_auth) supports authentication using ssh-agent.

Could this be added [here](https://github.com/SatelliteQE/broker/blob/master/broker/session.py#L61) additionally to password and key file?

There are setups where for security reasons the password is not given and only login via ssh-key is allowed. Furthermore the key is stored in the agent as not to be leaked in any CI setup.

**Comment by dosas** [comment]
@JacobCallahan yes that is exaclty what I was thinking about :) Very nice.

I came accross this project when trying to run some tests with robottelo.

**Comment by JacobCallahan** [comment]
Ahh nice, welcome!

**Comment by dosas** [comment]
Should I create a PR?

**Comment by JacobCallahan** [comment]
@dosas If you're willing to propose the change and run through a few test scenarios, then please do!

**Comment by dosas** [comment]
I could not find any tests for session, what do you mean by run through a few test scenarios?

**Comment by JacobCallahan** [comment]
@dosas since you can't really run our functional tests (no access to internal resources), then that would be manual tests using the different authentication methods against a remote host of your own. Of course, please sanitize any sensitive information.

```python
# key-based auth
test_host = Host(hostname="my.test.host", key_filename="/path/to/key")
assert test_host.hostname in test_host.execute("hostname").stdout


# password-based auth
test_host = Host(hostname="my.test.host", username="myuser", password="mypassword")
assert test_host.hostname in test_host.execute("hostname").stdout


# agent-based auth
test_host = Host(hostname="my.test.host", username="myuser")
assert test_host.hostname in test_host.execute("hostname").stdout
```
