### ISSUE TITLE
Provide a CLI method to print nicks

### ISSUE THREAD

**Issue by ehelms** [SatelliteQE/broker#312]
I am a heavy user of the `nicks` feature within the `broker_settings.yaml` file. I am prone to forgetting the names of each and then have to `cat ~/.config/broker/broker_settings.yaml` to remind myself. I would find it useful to be able to print these nick names from the CLI.

**Comment by JacobCallahan** [comment]
@ehelms would you just want a list of nicks or their fields as well?
Maybe it would make more sense to roll this into a larger feature allowing users to view/modify sections of their config.

**Comment by ehelms** [comment]
I use descriptive enough nicks that I do not need to see their properties. Simply the list of nicks would be fine. For example, I have the following:

```
  rhel8
  rhel9
  stream
  streamcap
  sat616
  sat615
  sat614
  sat613
  sat612
  sat611
  cap615
```

**Comment by JacobCallahan** [comment]
This will be delivered in 0.6
