### ISSUE TITLE
After machines are started up in RHVM, broker inventory --sync AnsibleTower --details didn't sync them properly. 

### ISSUE THREAD

**Issue by tstrych** [SatelliteQE/broker#33]
Initial state: 
5 sat machines :) 
1 up 4 down in satlab, and broker  showing them properly 

These commands work correctly, (only the result of first one is pasted below) 
`broker inventory --sync AnsibleTower`
`broker inventory --sync AnsibleTower --details` 
```
[INFO 200804 12:27:30] Adding new hosts: tstrych-satellite-6.8-latest-1595494906
[INFO 200804 12:27:30] Removing old hosts: dhcp-3-234.vms.sat.rdu2.redhat.com
[INFO 200804 12:27:30] Pulling local inventory
[INFO 200804 12:27:30] 0: dhcp-3-182.vms.sat.rdu2.redhat.com
[INFO 200804 12:27:30] 1: tstrych-satellite-6.8-latest-1596013441
[INFO 200804 12:27:30] 2: tstrych-satellite-6.8-latest-1596013720
[INFO 200804 12:27:30] 3: tstrych-satellite-6.8-latest-1596014889
[INFO 200804 12:27:30] 4: tstrych-satellite-6.8-latest-1595494906
```

As machine 1-4 were down, I run them up directly in satlab. 
After that, (there were some minutes between my actions)

command  `broker inventory --sync AnsibleTower --details ` was started but as you can see only the machine which ran before is shown. 

```
[INFO 200804 13:26:55] Pulling remote inventory from AnsibleTower
[INFO 200804 13:27:00] Adding new hosts: dhcp-3-234.vms.sat.rdu2.redhat.com, dhcp-3-72.vms.sat.rdu2.redhat.com, dhcp-3-34.vms.sat.rdu2.redhat.com, dhcp-3-66.vms.sat.rdu2.redhat.com
[INFO 200804 13:27:00] Removing old hosts: tstrych-satellite-6.8-latest-1596013441, tstrych-satellite-6.8-latest-1596013720, tstrych-satellite-6.8-latest-1596014889, tstrych-satellite-6.8-latest-1595494906
[INFO 200804 13:27:00] Pulling local inventory
[INFO 200804 13:27:00] 0: dhcp-3-182.vms.sat.rdu2.redhat.com, Details: _broker_args:
      new_expire_time: '+604800'
      target_vm: tstrych-satellite-6.8-latest-1595838167
    _broker_provider: AnsibleTower
    hostname: dhcp-3-182.vms.sat.rdu2.redhat.com
    name: tstrych-satellite-6.8-latest-1595838167
    type: host
```

Right after that I ran `broker inventory --sync AnsibleTower ` and all vm's were fetched successfully. 
```
[INFO 200804 13:27:30] Pulling remote inventory from AnsibleTower
[INFO 200804 13:27:35] Adding new hosts: dhcp-3-234.vms.sat.rdu2.redhat.com, dhcp-3-72.vms.sat.rdu2.redhat.com, dhcp-3-34.vms.sat.rdu2.redhat.com, dhcp-3-66.vms.sat.rdu2.redhat.com
[INFO 200804 13:27:35] Pulling local inventory
[INFO 200804 13:27:35] 0: dhcp-3-182.vms.sat.rdu2.redhat.com
[INFO 200804 13:27:35] 1: dhcp-3-234.vms.sat.rdu2.redhat.com
[INFO 200804 13:27:35] 2: dhcp-3-72.vms.sat.rdu2.redhat.com
[INFO 200804 13:27:35] 3: dhcp-3-34.vms.sat.rdu2.redhat.com
[INFO 200804 13:27:35] 4: dhcp-3-66.vms.sat.rdu2.redhat.com
```
There should be more investigation from my side as I don't know if just first sync does not work correctly, or if the problem is in details command.  I just want to address this problem here :)

**Comment by JacobCallahan** [comment]
@tstrych are you still seeing this issue?

**Comment by mshriver** [comment]
@JacobCallahan @tstrych I can confirm this behavior, as I just ran a `checkin` against my entire inventory, and then on an inventory sync all of the VMs were re-added to my inventory. Trying to check them in again resulted in the checkin workflow failing, because the VM passed no longer exists.

**Comment by JacobCallahan** [comment]
@mshriver that is likely an issue on AT's end. This issue can almost certainly be closed.
