### ISSUE TITLE
[RFE]: checkin multiple VMs  

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/broker#42]
Right now I can checkin VMs one by one or use --all, but in practice I often want to return several but not all VMs. A parameter accepting say comma separated list of  VM IDs would be helpful for these situations:

`broker checkin --some 0,2,4`

**Comment by JacobCallahan** [comment]
@pondrejk try `broker checkin 0 2 4`

**Comment by mshriver** [comment]
This behavior is supported with the syntax @JacobCallahan specified above.
