### ISSUE TITLE
[RFE] Implement VM snapshots handling

### ISSUE THREAD

**Issue by vsedmik** [SatelliteQE/broker#54]
In several cases I found useful the possibility of snapshotting the VM state and restoring it later (for example when using a setup which takes a while to create and you need to run some test repeatedly from certain point), which is not currently possible through the VM portal.

Is it possible (and worth it) to implement this functionality into broker?

**Comment by JacobCallahan** [comment]
This is something that would need to be introduced at the provider level. First-class broker support could then follow if needed.

**Comment by JacobCallahan** [comment]
This has been implemented in AnsibleTower, but will not get first-class support via Broker.
