### ISSUE TITLE
Race condition danger when using multiple instances of broker

### ISSUE THREAD

**Issue by jarovo** [SatelliteQE/broker#65]
In PR https://github.com/SatelliteQE/broker/pull/53 I am introducing a fix for handling the inventory in the *checkout* being done in concurrent mode, but as @mshriver just noted to me that even with that PR merged, there still gonna be a danger when using the broker "in background" fashion.

There is no mechanism for exclusive access involved when writing the inventory file in `update_inventory`. And there is an time interval when we can get race condition. We are dealing with classing multiple Readers/Writters concurrency problem here. https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock

**Comment by JacobCallahan** [comment]
This has been resolved via file locking for a while now, closing.
