### ISSUE TITLE
Initial VM Provider list

### ISSUE THREAD

**Issue by dsesami** [SatelliteQE/broker#7]
What providers would we want to support in an initial list of VM provisioning services?

This issue is about assembling a handful of services that we could strive to include, initially.  If I'm misunderstanding project goals, feel free to rehash, but in my mind, this would include things like being able to grab a VM with relevant info arbitrarily from things like:

* AWS
* Google Cloud
* Azure
* Tower/Satellite capabilities here? I know that's somewhat implemented, but what other products would be used?

What items would we want to support first and foremost? What are the most commonly useful ones in this case when dealing with different providers?

**Comment by kedark3** [comment]
In addition to what Dany is saying, I'd like us all to agree on Apart from RH Virt/Cloud providers, what other providers from Public Cloud domain are most used in QE. That will help us focus our effort on delivering a small initial set of features for that provider.

**Comment by JacobCallahan** [comment]
+1 to focusing on the most used ones first. Libvirt local/remote is the first that comes to mind.
We could also leverage libraries like wrapanapi that may already abstract interaction with desired providers. @mshriver could speak more to that.
