### ISSUE TITLE
For AnsibleTower provider, _merge_artifacts needs to be changed to `last`

### ISSUE THREAD

**Issue by bherrin3** [SatelliteQE/broker#74]
## Problem

In Pipelines, if a WF is changed or permissioned incorrectly, the assumed `artifacts` can be incorrect resulting in `remove` `broker` calls to fail with inaccurate information

* https://github.com/SatelliteQE/broker/blob/9e72c6d7f61410db7980303a730d372a852cf5b7/broker/providers/ansible_tower.py#L95

## Solution

Move to a `_merge_artifacts` implementation for `last`.

## Concerns

This is going to be an integration test effort with AT WFs to ensure that, for the desired `broker` actions, the correct information is returned in `last`.

Initial best testing solution seems to be baselining the initial returns to Jenkins based standards and adapting WFs to `broker` running in `last`.

**Comment by bherrin3** [comment]
@JacobCallahan I will setup the test side and send you those details. Good luck at the park.

**Comment by JacobCallahan** [comment]
This has been resolved.
