### ISSUE TITLE
RFE: Implement proper exit codes when using broker from CLI

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/broker#91]
It would be useful especially for jenkins pipelines if we could simply assert on the `broker` command results by looking at the exit codes.

e.g. for `broker exec --workflow`, I'd like to see a non-zero return code in case the executed workflow fails. More granularity might be eventually introduced (to distinguish between the failure happening in the workflow itself, or broker unable to actually execute it for some reason [non-existing workflow, permission issues,...])

right now:
```
$ broker execute --workflow nonexistent
[INFO 210310 11:17:37] Using provider AnsibleTower for execution
[INFO 210310 11:17:37] Using username and password authentication
[ERROR 210310 11:17:39] Workflow not found by name: nonexistent
[INFO 210310 11:17:39] None
$ echo $?
0

```

**Comment by JacobCallahan** [comment]
This is done in broker 0.1.11+
